import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { SanityLive } from "../../lib/live";

export const metadata: Metadata = {
  title: "PrimePick",
  description: "Generated by Nish Patel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main>
            <Header />
            {children}
          </main>
          <SanityLive></SanityLive>
        </body>
      </html>
    </ClerkProvider>
  );
}
