import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { SanityLive } from "../../lib/live";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisableDraftMode } from "@/components/DisabelDraftMode";

export const metadata: Metadata = {
  title: "PrimePick",
  description: "Generated by Nish Patel",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        {/* ✅ Ensure full-page flexbox layout */}
        <body className="flex flex-col min-h-screen overflow-x-hidden">
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}

          {/* ✅ Keep the Header at the top */}
          <Header />

          {/* ✅ Main content should take up all available space */}
          <main className="flex-1">{children}</main>

          {/* ✅ Footer sticks to the bottom */}
          <Footer />

          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
